### ISSUE TITLE
Elixir Türkiye Sitesi açılmıyor.

### ISSUE THREAD

**Issue by enderahmetyurt** [elixirtr/elixirtr#4]
https://elixirturkiye.org uzun süre bekledikten sonra timeout oluyor. FF Quantum 66.0.3 MacOS Mojave 10.14.4

**Comment by murat** [comment]
@kakkoyun #5 i merge ettikten sonra deploy edelim artık girmeyi deneyen oluyor bak. :)

**Comment by kakkoyun** [comment]
Tamam tamam, mesaj alindi 🙈

**Comment by kakkoyun** [comment]
@enderahmetyurt Cok tesekkurler geri bildirim icin. Cok yakinda https://www.elixirturkiye.com ve https://www.elixirturkiye.org adreslerinde yayina girmis olacak umarim.

Henuz yolun cok basindayiz, Ruby Turkiye'deki tecrubelerinizi goz onune alarak, yol gosterirseniz seviniriz.

**Comment by enderahmetyurt** [comment]
Yolunuz açık olsun valla. Güzel işler bunlar. Tek tavsiyem yapacağınız şeye inanın ve keyif alın :) Türkiye'de bu topluluk işleri cidden çok moral bozucu olabiliyor zaman zaman. Pek fazla kulak asmayın derim. Teknik olarak ise topluluk sitesini sade tutun bence bir de bir şeyi bitirmediyseniz release ettik demeyin benim gibiler issue açar :)
